---

- name: Create kube-core namespace
  kubernetes.core.k8s:
    name: "{{ kube_gitops_namespace }}"
    api_version: v1
    kind: Namespace
    state: present
    wait: true

- name: Install Argo cd
  become: true
  block:

    - name: Install argocd repository
      kubernetes.core.helm_repository:
        name: argo-cd
        repo_url: https://argoproj.github.io/argo-helm

    - name: Install argocd
      kubernetes.core.helm:
        name: argo-cd
        chart_ref: argo-cd/argo-cd
        release_namespace: "{{ kube_gitops_namespace }}"
        values: "{{ lookup('template', 'argo.yml.j2') | from_yaml }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::argocd