---
phpmyadmin:
  deployed: true

  #
  # Meta
  #
  name: mysql-admin-ui
  namespace: "{{ kube_data_namespace }}"

  #
  # Middleware
  #
  traefik_middleware: []

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - containerPort: 80
      env: 
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
          
  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

  tls:
    - hosts:
        - "{{ mysql_admin_domain }}"
      secretName: "{{ mysql_admin_domain }}-tls"

  ingress_rules:
    - host: "{{ mysql_admin_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mysql-admin-ui
                port:
                  number: 80
