---

- name: Grant admin rights to Kubernetes
  become: true
  block:
    - name: Create .kube folder in home
      file:
        path: "/home/{{ item }}/.kube"
        state: directory
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0700

    - name: Copy root kubeconfig file
      copy:
        src: /root/.kube/config
        dest: "/home/{{ item }}/.kube/config"
        remote_src: yes
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: 0600

    - name: Set KUBECONFIG env var in .bashrc
      lineinfile:
        path: "/home/{{ item }}/.bashrc"
        regexp: '^export KUBECONFIG='
        line: "export KUBECONFIG=/home/{{ item }}/.kube/config"


