releases:
  # Chart version
  version:
    # STORAGE
    storage-snapshot-controller: 0.2.4
    storage-hdd-block: 0.14.2
    storage-hdd-file: 0.14.2
    storage-ssd-block: 0.14.2
    storage-ssd-file: 0.14.2

    # NETWORK
    traefik: v25.0.0
    e-dns-cloudflare: 6.13.2
    error-pages: 1.2.2
    cert-manager: 1.14.2
    network-config: 1.1.0

    # ACCESS
    teleport: 14.3.0

    # MONITOR
    loki-stack: 2.7.0
    prometheus-stack: 40.5.0
    monitor-config: 1.0.0

    # EXTRA-OPERATOR
    strimzi: 0.33.2

  installed:
    # STORAGE
    storage-hdd-block: true
    storage-hdd-file: true
    storage-ssd-block: true
    storage-ssd-file: true

    # NETWORK
    traefik: true
    e-dns-cloudflare: true
    error-pages: true
    cert-manager: true
    network-config: true

    # ACCESS
    teleport: true

    # MONITOR
    loki-stack: true
    prometheus-stack: true
    monitor-config: true

    # EXTRA-OPERATOR
    strimzi: true

apps:
  version:
    traefik: v2.9
    errorPages: 2.18.0
    whoami: v1.8.6
    alertManager: v0.24.0
    grafana: 8.3.3
