---

- name: Install Mysql Server
  become: true
  block:

    - name: "Deploy mysql secret"
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'mysql/secret.yml.j2') }}"

    - name: Install bitnami repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "{{ bitnami_charts_url }}"

    - name: Install Mysql cluster
      kubernetes.core.helm:
        name: mysql
        chart_ref: bitnami/mysql
        release_namespace: "{{ kube_data_namespace }}"
        values: "{{ lookup('template', 'mysql/values.yml.j2') | from_yaml }}"
        wait: yes

    - name: Install db-operator repository
      kubernetes.core.helm_repository:
        name: db-operator
        repo_url: "{{ dboperator_charts_url }}"

    - name: Install DB op√©rator
      kubernetes.core.helm:
        name: db-operator
        chart_ref: db-operator/db-operator
        release_namespace: "{{ kube_data_namespace }}"
        values: "{{ lookup('template', 'mysql/operator.yml.j2') | from_yaml }}"
        wait: yes
    
    - name: "Deploy db instance"
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'mysql/instance.yml.j2') }}"
    
    - name: "Deploy db instance"
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'mysql/database.yml.j2') }}"

    - name: Deploy phpmyadmin app
      vars:
        app: "{{ phpmyadmin }}"
      import_role:
        name: roles/kube-apps
        tasks_from: custom

  tags:
    - kubernetes
    - kubernetes::data
    - kubernetes::data::mysql