---

- name: Manage declared applications
  include_tasks: custom.yml
  when: app.deployType == "custom"
  loop: "{{ applications }}"
  loop_control:
    loop_var: app

- name: Manage declared Project
  include_tasks: argocd-project.yml
  when: app.deployType == "argocd"
  loop: "{{ applications }}"
  loop_control:
    loop_var: app
