---
server_users:
  brice_michalski:
    uid: 1000
    gid: 1000
    admin: true
    group: brice_michalski
    groups: adm,cdrom,sudo,dip,plugdev,lxd
    comment: Brice Michalski
    public_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/oa/vf2NNMghjlV+wMc5Me6YDK6DMet5oH0yA+zS7cVihrTwNTm8EM1g8bOQODxgC5BaZlN6GBXqagyOfGmDyouDeGtccL/9leiDNlM23B1Kf8f6AQc1NcjNCVZSikKUDZy9ni/okiD5PsbyZa1atjk8aQZ/wxJsqwdBY59f/zA0Ou60xuYFVwrRsgPQ1/MTWa7SRGHyNdxnDNu/9qn7SwAGdnvtig8O4d9pKX9dMMyymOhrRkFTipmMa7NAISIQGxbBpYyiVDCS/Yhbl50odZOcMgAwcRoVrLZKFBUE38PLcoLwHdesLybsjWTIFFkplPonr9Wm3RevMpv4JpjpL" # yamllint disable-line
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgauaVLI/2tiMTq/wUcejDQys6ZP3uWSKIEI0Qw7AjmXu+Wa1FMQHt7Rs+9eUm5AjSLEsUUrH3D1/VizbE++d3mLBvDpkeBiFiLuGyul2b085OUO5XgN+yfd+AWKOEzqPwJkNfSVOZ1/2kD/6bE7wvNcN+sSGZhZdCAJDtWTzbzqxytbEAisHPb38c+J7A4mcP7sAN8A2WtqlWvMa5ggDjJ1hxvb7FrwspBZHhQc94FGXeBcQjaGDyf6OxqNjY58WZhjXeQmWsxSqV1ZLHEUZaBpecF46wIILOPWeYWSbvT3KZCGRL6jyj6CQNGCQrEg2nI2R15DeFTgN+oSkMu+nhMgm76E87UTbJJxNdDoHhOP7e+4sjNNKNJec056PxlxIaK4Jav9BVDtDFc9p36ExjBERbIuRiKw7ZmN/SjAVnrqOkxMQp5QvoncfOKBAolN/XMMV0YI8oFVqndA9gC7jpGDDri7qyeO5Kz+enbh4My1xNttlxdmwvUkFhVeY4SFs= bricemichalski@briceHome" # yamllint disable-line
